'use client';
import {useEffect,useRef,useState} from 'react';
import {audioBands} from '@/lib/audio-bands';
import Shader from './shader';
const quiet=Array(8).fill(0) as number[];
export default function AudioReactive(){const [bands,setBands]=useState(quiet),[mode,setMode]=useState<'idle'|'requesting'|'active'>('idle'),[notice,setNotice]=useState(''),[supported,setSupported]=useState(true),[reduced,setReduced]=useState(false);const streamRef=useRef<MediaStream|null>(null),contextRef=useRef<AudioContext|null>(null),frameRef=useRef(0),mounted=useRef(true),pending=useRef(false);
function release(){cancelAnimationFrame(frameRef.current);streamRef.current?.getTracks().forEach(t=>{t.onended=null;t.stop()});streamRef.current=null;const context=contextRef.current;contextRef.current=null;if(context&&context.state!=='closed')void context.close().catch(()=>{});if(mounted.current){setMode('idle');setBands(quiet)}}
useEffect(()=>{mounted.current=true;setSupported(!!navigator.mediaDevices?.getDisplayMedia);const motion=window.matchMedia('(prefers-reduced-motion: reduce)');setReduced(motion.matches);const changed=()=>setReduced(motion.matches);motion.addEventListener('change',changed);return()=>{mounted.current=false;motion.removeEventListener('change',changed);release()}},[]);
async function connect(){if(pending.current)return;pending.current=true;setNotice('');setMode('requesting');try{const capture=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true,preferCurrentTab:true,systemAudio:'exclude'} as DisplayMediaStreamOptions);if(!mounted.current){capture.getTracks().forEach(t=>t.stop());return}streamRef.current=capture;const surface=capture.getVideoTracks()[0]?.getSettings().displaySurface;if(surface&&surface!=='browser'){release();setNotice('Choose a browser tab with Share tab audio enabled. Windows and entire screens are not used.');return}const tracks=capture.getAudioTracks();if(!tracks.length){release();setNotice('No audio was shared. Try again, choose this tab, and enable “Share tab audio”. Chrome or Edge on desktop supports tab audio sharing.');return}const context=new AudioContext();contextRef.current=context;await context.resume();if(!mounted.current||streamRef.current!==capture)return;const source=context.createMediaStreamSource(new MediaStream(tracks)),analyser=context.createAnalyser();analyser.fftSize=2048;analyser.minDecibels=-85;analyser.maxDecibels=-18;analyser.smoothingTimeConstant=.78;source.connect(analyser);const spectrum=new Uint8Array(analyser.frequencyBinCount);let smoothed=[...quiet],last=0;const tick=(time:number)=>{if(!mounted.current||streamRef.current!==capture)return;analyser.getByteFrequencyData(spectrum);const target=audioBands(spectrum,context.sampleRate,analyser.fftSize);smoothed=smoothed.map((old,i)=>old+(target[i]-old)*(target[i]>old?.34:.13));if(time-last>=33){setBands([...smoothed]);last=time}frameRef.current=requestAnimationFrame(tick)};capture.getTracks().forEach(track=>track.onended=()=>{release();setNotice('Audio sharing stopped. Connect again whenever you’re ready.')});setMode('active');frameRef.current=requestAnimationFrame(tick)}catch(error){release();const name=error instanceof DOMException?error.name:'';setNotice(name==='NotAllowedError'?'Audio sharing was cancelled or blocked. You can try again.':name==='NotSupportedError'?'Tab audio sharing is not available here. Open the site in desktop Chrome or Edge.':'Could not connect to tab audio. Try again in desktop Chrome or Edge.')}finally{pending.current=false}}
return <div className="shader-stage"><Shader bands={bands} reduced={reduced}/><div className="dot-control"><button type="button" className={`audio-dot ${mode==='active'?'is-listening':''}`} aria-label={mode==='active'?'Disable audio reactivity':'Enable audio reactivity'} aria-pressed={mode==='active'} title={mode==='active'?'Stop listening':'React to music: choose this tab and enable Share tab audio'} disabled={!supported||mode==='requesting'} onClick={mode==='active'?()=>{release();setNotice('')}:connect}><span/></button><span className="dot-help">{mode==='active'?'Sound on':supported?'Enable sound response':'Tab audio needs desktop Chrome or Edge'}</span></div>{notice&&<p role="status" className="shader-notice">{notice}</p>}</div>}
